services:
  server:
    container_name: test_api
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=testpostpass
      - PGDATABASE=test_postsdb
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=test_postsdb
      - POSTGRES_PASSWORD=testpostpass
volumes:
  test_db:
networks:
  default:
    name: debug_test
